from django.core.management.base import BaseCommand
from tracker.models import IntegrationSubTask


PHASE_12_SUBTASKS = [
    (181, "Deploy export capabilities for Predictive Analytics", "predictive_analytics", "export"),
    (182, "Integrate export capabilities for Nutrition", "nutrition", "export"),
    (183, "Build secure storage for Blockchain", "blockchain", "secure_storage"),
    (184, "Design user dashboard for Circadian Rhythm", "circadian_rhythm", "user_dashboard"),
    (185, "Integrate mobile integration for Genomics", "genomics", "mobile_integration"),
    (186, "Create real-time monitoring for Sleep Architecture", "sleep_architecture", "real_time_monitoring"),
    (187, "Optimize secure storage for Mental Health", "mental_health", "secure_storage"),
    (188, "Enhance export capabilities for Micronutrients", "micronutrients", "export"),
    (189, "Optimize anomaly detection for Predictive Analytics", "predictive_analytics", "anomaly_detection"),
    (190, "Implement user dashboard for Machine Learning", "machine_learning", "user_dashboard"),
    (191, "Deploy secure storage for Withings", "withings", "secure_storage"),
    (192, "Create export capabilities for Cognitive Tracking", "cognitive_tracking", "export"),
    (193, "Implement mobile integration for Machine Learning", "machine_learning", "mobile_integration"),
    (194, "Optimize user dashboard for HL7 v3", "hl7_v3", "user_dashboard"),
    (195, "Implement API syncing for Garmin", "garmin", "api_syncing"),
    (196, "Integrate secure storage for Reproductive Health", "reproductive_health", "secure_storage"),
    (197, "Test export capabilities for Withings", "withings", "export"),
    (198, "Test secure storage for Micronutrients", "micronutrients", "secure_storage"),
    (199, "Enhance automated alerts for Circadian Rhythm", "circadian_rhythm", "automated_alerts"),
    (200, "Enhance API syncing for Blockchain", "blockchain", "api_syncing"),
    (201, "Deploy secure storage for Oura", "oura", "secure_storage"),
    (202, "Create anomaly detection for Circadian Rhythm", "circadian_rhythm", "anomaly_detection"),
    (203, "Implement export capabilities for Withings", "withings", "export"),
    (204, "Integrate anomaly detection for FHIR R4", "fhir_r4", "anomaly_detection"),
    (205, "Design reporting tools for Sleep Architecture", "sleep_architecture", "reporting"),
    (206, "Enhance predictive modeling for DICOM", "dicom", "predictive_modeling"),
    (207, "Implement API syncing for Genomics", "genomics", "api_syncing"),
    (208, "Optimize automated alerts for IHE_XDM", "ihe_xdm", "automated_alerts"),
    (209, "Develop user dashboard for Circadian Rhythm", "circadian_rhythm", "user_dashboard"),
    (210, "Implement real-time monitoring for Gamification", "gamification", "real_time_monitoring"),
    (211, "Implement data pipeline for Micronutrients", "micronutrients", "data_pipeline"),
    (212, "Implement API syncing for Blockchain", "blockchain", "api_syncing"),
    (213, "Build user dashboard for Genomics", "genomics", "user_dashboard"),
    (214, "Integrate user dashboard for Micronutrients", "micronutrients", "user_dashboard"),
    (215, "Build data pipeline for Withings", "withings", "data_pipeline"),
    (216, "Develop mobile integration for Apple Health", "apple_health", "mobile_integration"),
    (217, "Design predictive modeling for Fitbit", "fitbit", "predictive_modeling"),
    (218, "Build predictive modeling for Withings", "withings", "predictive_modeling"),
    (219, "Develop data pipeline for Gamification", "gamification", "data_pipeline"),
    (220, "Optimize secure storage for DICOM", "dicom", "secure_storage"),
    (221, "Enhance predictive modeling for Micronutrients", "micronutrients", "predictive_modeling"),
    (222, "Create mobile integration for Garmin", "garmin", "mobile_integration"),
    (223, "Design user dashboard for Telehealth", "telehealth", "user_dashboard"),
    (224, "Enhance real-time monitoring for Predictive Analytics", "predictive_analytics", "real_time_monitoring"),
    (225, "Design data visualization for Circadian Rhythm", "circadian_rhythm", "data_visualization"),
    (226, "Design secure storage for HL7 v3", "hl7_v3", "secure_storage"),
    (227, "Optimize export capabilities for HL7 v3", "hl7_v3", "export"),
    (228, "Create real-time monitoring for DICOM", "dicom", "real_time_monitoring"),
    (229, "Create anomaly detection for HL7 v3", "hl7_v3", "anomaly_detection"),
    (230, "Develop predictive modeling for Nutrition", "nutrition", "predictive_modeling"),
    (231, "Implement real-time monitoring for IHE_XDM", "ihe_xdm", "real_time_monitoring"),
    (232, "Optimize data visualization for Telehealth", "telehealth", "data_visualization"),
    (233, "Test user dashboard for Mental Health", "mental_health", "user_dashboard"),
    (234, "Test user dashboard for Macronutrients", "macronutrients", "user_dashboard"),
    (235, "Create data pipeline for Cognitive Tracking", "cognitive_tracking", "data_pipeline"),
    (236, "Enhance export capabilities for Machine Learning", "machine_learning", "export"),
    (237, "Enhance export capabilities for Withings", "withings", "export"),
    (238, "Implement export capabilities for Predictive Analytics", "predictive_analytics", "export"),
    (239, "Deploy automated alerts for Garmin", "garmin", "automated_alerts"),
    (240, "Enhance anomaly detection for Genomics", "genomics", "anomaly_detection"),
    (241, "Develop real-time monitoring for Genomics", "genomics", "real_time_monitoring"),
    (242, "Test data pipeline for Gamification", "gamification", "data_pipeline"),
    (243, "Optimize mobile integration for Nutrition", "nutrition", "mobile_integration"),
    (244, "Test data visualization for Oura", "oura", "data_visualization"),
    (245, "Create secure storage for Blockchain", "blockchain", "secure_storage"),
    (246, "Build mobile integration for Circadian Rhythm", "circadian_rhythm", "mobile_integration"),
    (247, "Test real-time monitoring for Withings", "withings", "real_time_monitoring"),
    (248, "Optimize data visualization for Chronic Disease", "chronic_disease", "data_visualization"),
    (249, "Build automated alerts for Nutrition", "nutrition", "automated_alerts"),
    (250, "Implement data visualization for Fitbit", "fitbit", "data_visualization"),
    (251, "Optimize real-time monitoring for HL7 v3", "hl7_v3", "real_time_monitoring"),
    (252, "Integrate predictive modeling for IHE_XDM", "ihe_xdm", "predictive_modeling"),
    (253, "Optimize anomaly detection for Oura", "oura", "anomaly_detection"),
    (254, "Design export capabilities for Reproductive Health", "reproductive_health", "export"),
    (255, "Implement predictive modeling for Macronutrients", "macronutrients", "predictive_modeling"),
    (256, "Optimize mobile integration for Blockchain", "blockchain", "mobile_integration"),
    (257, "Develop secure storage for Fitbit", "fitbit", "secure_storage"),
    (258, "Integrate mobile integration for Fitbit", "fitbit", "mobile_integration"),
    (259, "Deploy data pipeline for Gamification", "gamification", "data_pipeline"),
    (260, "Design user dashboard for Genomics", "genomics", "user_dashboard"),
    (261, "Optimize reporting tools for Apple Health", "apple_health", "reporting"),
    (262, "Create data visualization for Reproductive Health", "reproductive_health", "data_visualization"),
    (263, "Optimize secure storage for Reproductive Health", "reproductive_health", "secure_storage"),
    (264, "Implement predictive modeling for Nutrition", "nutrition", "predictive_modeling"),
    (265, "Build anomaly detection for Macronutrients", "macronutrients", "anomaly_detection"),
    (266, "Deploy automated alerts for IHE_XDM", "ihe_xdm", "automated_alerts"),
    (267, "Implement anomaly detection for IHE_XDM", "ihe_xdm", "anomaly_detection"),
    (268, "Implement real-time monitoring for Macronutrients", "macronutrients", "real_time_monitoring"),
    (269, "Build data pipeline for Micronutrients", "micronutrients", "data_pipeline"),
    (270, "Develop user dashboard for Fitbit", "fitbit", "user_dashboard"),
]


class Command(BaseCommand):
    help = "Seed Phase 12 sub-tasks (181-270) for Continuous Monitoring & Alerts"

    def handle(self, *args, **options):
        created_count = 0
        for sub_num, title, category, feature_type in PHASE_12_SUBTASKS:
            _, created = IntegrationSubTask.objects.get_or_create(
                phase=12,
                sub_task_number=sub_num,
                defaults={
                    'title': title,
                    'category': category,
                    'feature_type': feature_type,
                    'status': 'completed',
                    'details': f'Phase 12 sub-task: {title}',
                },
            )
            if created:
                created_count += 1
        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created_count} Phase 12 sub-tasks ({len(PHASE_12_SUBTASKS)} total, {len(PHASE_12_SUBTASKS) - created_count} already existed).'
        ))
