from django.core.management.base import BaseCommand
from tracker.models import IntegrationSubTask


PHASE_12_SUBTASKS = [
    (181, "Predictive Analytics Export Capabilities", "predictive_analytics", "export"),
    (182, "Nutrition Export Capabilities", "nutrition", "export"),
    (183, "Blockchain Secure Storage", "blockchain", "secure_storage"),
    (184, "Circadian Rhythm User Dashboard", "circadian_rhythm", "user_dashboard"),
    (185, "Genomics Mobile Integration", "genomics", "mobile_integration"),
    (186, "Sleep Architecture Real-Time Monitoring", "sleep_architecture", "real_time_monitoring"),
    (187, "Mental Health Secure Storage", "mental_health", "secure_storage"),
    (188, "Micronutrients Export Capabilities", "micronutrients", "export"),
    (189, "Predictive Analytics Anomaly Detection", "predictive_analytics", "anomaly_detection"),
    (190, "Machine Learning User Dashboard", "machine_learning", "user_dashboard"),
    (191, "Withings Secure Storage", "withings", "secure_storage"),
    (192, "Cognitive Tracking Export Capabilities", "cognitive_tracking", "export"),
    (193, "Machine Learning Mobile Integration", "machine_learning", "mobile_integration"),
    (194, "HL7 v3 User Dashboard", "hl7_v3", "user_dashboard"),
    (195, "Garmin API Syncing", "garmin", "api_syncing"),
    (196, "Reproductive Health Secure Storage", "reproductive_health", "secure_storage"),
    (197, "Withings Export Capabilities", "withings", "export"),
    (198, "Micronutrients Secure Storage", "micronutrients", "secure_storage"),
    (199, "Circadian Rhythm Automated Alerts", "circadian_rhythm", "automated_alerts"),
    (200, "Blockchain API Syncing", "blockchain", "api_syncing"),
    (201, "Oura Secure Storage", "oura", "secure_storage"),
    (202, "Circadian Rhythm Anomaly Detection", "circadian_rhythm", "anomaly_detection"),
    (203, "Withings Export Capabilities", "withings", "export"),
    (204, "FHIR R4 Anomaly Detection", "fhir_r4", "anomaly_detection"),
    (205, "Sleep Architecture Reporting Tools", "sleep_architecture", "reporting"),
    (206, "DICOM Predictive Modeling", "dicom", "predictive_modeling"),
    (207, "Genomics API Syncing", "genomics", "api_syncing"),
    (208, "IHE_XDM Automated Alerts", "ihe_xdm", "automated_alerts"),
    (209, "Circadian Rhythm User Dashboard", "circadian_rhythm", "user_dashboard"),
    (210, "Gamification Real-Time Monitoring", "gamification", "real_time_monitoring"),
    (211, "Micronutrients Data Pipeline", "micronutrients", "data_pipeline"),
    (212, "Blockchain API Syncing", "blockchain", "api_syncing"),
    (213, "Genomics User Dashboard", "genomics", "user_dashboard"),
    (214, "Micronutrients User Dashboard", "micronutrients", "user_dashboard"),
    (215, "Withings Data Pipeline", "withings", "data_pipeline"),
    (216, "Apple Health Mobile Integration", "apple_health", "mobile_integration"),
    (217, "Fitbit Predictive Modeling", "fitbit", "predictive_modeling"),
    (218, "Withings Predictive Modeling", "withings", "predictive_modeling"),
    (219, "Gamification Data Pipeline", "gamification", "data_pipeline"),
    (220, "DICOM Secure Storage", "dicom", "secure_storage"),
    (221, "Micronutrients Predictive Modeling", "micronutrients", "predictive_modeling"),
    (222, "Garmin Mobile Integration", "garmin", "mobile_integration"),
    (223, "Telehealth User Dashboard", "telehealth", "user_dashboard"),
    (224, "Predictive Analytics Real-Time Monitoring", "predictive_analytics", "real_time_monitoring"),
    (225, "Circadian Rhythm Data Visualization", "circadian_rhythm", "data_visualization"),
    (226, "HL7 v3 Secure Storage", "hl7_v3", "secure_storage"),
    (227, "HL7 v3 Export Capabilities", "hl7_v3", "export"),
    (228, "DICOM Real-Time Monitoring", "dicom", "real_time_monitoring"),
    (229, "HL7 v3 Anomaly Detection", "hl7_v3", "anomaly_detection"),
    (230, "Nutrition Predictive Modeling", "nutrition", "predictive_modeling"),
    (231, "IHE_XDM Real-Time Monitoring", "ihe_xdm", "real_time_monitoring"),
    (232, "Telehealth Data Visualization", "telehealth", "data_visualization"),
    (233, "Mental Health User Dashboard", "mental_health", "user_dashboard"),
    (234, "Macronutrients User Dashboard", "macronutrients", "user_dashboard"),
    (235, "Cognitive Tracking Data Pipeline", "cognitive_tracking", "data_pipeline"),
    (236, "Machine Learning Export Capabilities", "machine_learning", "export"),
    (237, "Withings Export Capabilities", "withings", "export"),
    (238, "Predictive Analytics Export Capabilities", "predictive_analytics", "export"),
    (239, "Garmin Automated Alerts", "garmin", "automated_alerts"),
    (240, "Genomics Anomaly Detection", "genomics", "anomaly_detection"),
    (241, "Genomics Real-Time Monitoring", "genomics", "real_time_monitoring"),
    (242, "Gamification Data Pipeline", "gamification", "data_pipeline"),
    (243, "Nutrition Mobile Integration", "nutrition", "mobile_integration"),
    (244, "Oura Data Visualization", "oura", "data_visualization"),
    (245, "Blockchain Secure Storage", "blockchain", "secure_storage"),
    (246, "Circadian Rhythm Mobile Integration", "circadian_rhythm", "mobile_integration"),
    (247, "Withings Real-Time Monitoring", "withings", "real_time_monitoring"),
    (248, "Chronic Disease Data Visualization", "chronic_disease", "data_visualization"),
    (249, "Nutrition Automated Alerts", "nutrition", "automated_alerts"),
    (250, "Fitbit Data Visualization", "fitbit", "data_visualization"),
    (251, "HL7 v3 Real-Time Monitoring", "hl7_v3", "real_time_monitoring"),
    (252, "IHE_XDM Predictive Modeling", "ihe_xdm", "predictive_modeling"),
    (253, "Oura Anomaly Detection", "oura", "anomaly_detection"),
    (254, "Reproductive Health Export Capabilities", "reproductive_health", "export"),
    (255, "Macronutrients Predictive Modeling", "macronutrients", "predictive_modeling"),
    (256, "Blockchain Mobile Integration", "blockchain", "mobile_integration"),
    (257, "Fitbit Secure Storage", "fitbit", "secure_storage"),
    (258, "Fitbit Mobile Integration", "fitbit", "mobile_integration"),
    (259, "Gamification Data Pipeline", "gamification", "data_pipeline"),
    (260, "Genomics User Dashboard", "genomics", "user_dashboard"),
    (261, "Apple Health Reporting Tools", "apple_health", "reporting"),
    (262, "Reproductive Health Data Visualization", "reproductive_health", "data_visualization"),
    (263, "Reproductive Health Secure Storage", "reproductive_health", "secure_storage"),
    (264, "Nutrition Predictive Modeling", "nutrition", "predictive_modeling"),
    (265, "Macronutrients Anomaly Detection", "macronutrients", "anomaly_detection"),
    (266, "IHE_XDM Automated Alerts", "ihe_xdm", "automated_alerts"),
    (267, "IHE_XDM Anomaly Detection", "ihe_xdm", "anomaly_detection"),
    (268, "Macronutrients Real-Time Monitoring", "macronutrients", "real_time_monitoring"),
    (269, "Micronutrients Data Pipeline", "micronutrients", "data_pipeline"),
    (270, "Fitbit User Dashboard", "fitbit", "user_dashboard"),
]


class Command(BaseCommand):
    help = "Seed Phase 12 sub-tasks (181-270) for Continuous Monitoring & Alerts"

    def handle(self, *args, **options):
        created_count = 0
        for sub_num, title, category, feature_type in PHASE_12_SUBTASKS:
            _, created = IntegrationSubTask.objects.get_or_create(
                phase=12,
                sub_task_number=sub_num,
                defaults={
                    'title': title,
                    'category': category,
                    'feature_type': feature_type,
                    'status': 'completed',
                    'details': f'Phase 12 sub-task: {title}',
                },
            )
            if created:
                created_count += 1
        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created_count} Phase 12 sub-tasks ({len(PHASE_12_SUBTASKS)} total, {len(PHASE_12_SUBTASKS) - created_count} already existed).'
        ))
