# Generated by Django 6.0.2 on 2026-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("normal_min", models.FloatField(blank=True, null=True)),
                ("normal_max", models.FloatField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BloodTestInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100, unique=True)),
                ("unit", models.CharField(max_length=20)),
                ("normal_min", models.FloatField(blank=True, null=True)),
                ("normal_max", models.FloatField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
