# Generated by Django 6.0.2 on 2026-03-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('summary_cards', 'Summary Cards'), ('recent_results', 'Recent Blood Results'), ('vital_signs', 'Latest Vital Signs'), ('blood_charts', 'Blood Test Charts'), ('vitals_charts', 'Vital Signs Charts'), ('comparative_bars', 'Comparative Bar Charts'), ('boxplots', 'Box Plots')], max_length=50, unique=True)),
                ('position', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DataPointAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='tracker.bloodtest')),
                ('vital_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='tracker.vitalsign')),
            ],
        ),
    ]
