# Generated by Django 6.0.2 on 2026-03-01 20:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('skeletal_muscle_mass', models.FloatField(blank=True, null=True)),
                ('bone_density', models.FloatField(blank=True, null=True)),
                ('waist_circumference', models.FloatField(blank=True, null=True)),
                ('hip_circumference', models.FloatField(blank=True, null=True)),
                ('waist_to_hip_ratio', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CustomVitalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyFatigueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HydrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fluid_intake_ml', models.FloatField()),
                ('goal_ml', models.FloatField(blank=True, default=2500, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='KetoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('measurement_type', models.CharField(choices=[('blood', 'Blood (mmol/L)'), ('urine', 'Urine (mg/dL)'), ('breath', 'Breath (ppm)')], default='blood', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MetabolicLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blood_glucose', models.FloatField(blank=True, null=True)),
                ('insulin_level', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='OrthostaticReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supine_hr', models.IntegerField(blank=True, null=True)),
                ('standing_hr', models.IntegerField(blank=True, null=True)),
                ('supine_systolic', models.IntegerField(blank=True, null=True)),
                ('supine_diastolic', models.IntegerField(blank=True, null=True)),
                ('standing_systolic', models.IntegerField(blank=True, null=True)),
                ('standing_diastolic', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_region', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('left_shoulder', 'Left Shoulder'), ('right_shoulder', 'Right Shoulder'), ('chest', 'Chest'), ('upper_back', 'Upper Back'), ('lower_back', 'Lower Back'), ('abdomen', 'Abdomen'), ('left_arm', 'Left Arm'), ('right_arm', 'Right Arm'), ('left_hand', 'Left Hand'), ('right_hand', 'Right Hand'), ('left_hip', 'Left Hip'), ('right_hip', 'Right Hip'), ('left_leg', 'Left Leg'), ('right_leg', 'Right Leg'), ('left_knee', 'Left Knee'), ('right_knee', 'Right Knee'), ('left_foot', 'Left Foot'), ('right_foot', 'Right Foot')], max_length=50)),
                ('pain_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ReproductiveHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cycle_day', models.IntegerField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], default='', max_length=20)),
                ('flow_intensity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RestingMetabolicRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('formula', models.CharField(choices=[('mifflin', 'Mifflin-St Jeor'), ('harris', 'Harris-Benedict')], default='mifflin', max_length=20)),
                ('rmr_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom', models.CharField(max_length=200)),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Very Severe'), (5, 'Extreme')], default=1)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='bbt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomVitalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('notes', models.TextField(blank=True, default='')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.customvitaldefinition')),
            ],
        ),
    ]
