# Generated by Django 6.0.2 on 2026-03-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bodycomposition_customvitaldefinition_and_more'),
        ('tracker', '0002_dashboardwidget_datapointannotation'),
    ]

    operations = [
    ]
