# Generated by Django 6.0.2 on 2026-03-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_admintelemetry_apiratelimitconfig_auditlog_and_more'),
        ('tracker', '0004_privacypreference_securitylog_userprofile_and_more'),
    ]

    operations = [
    ]
