# Generated by Django 6.0.2 on 2026-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_admintelemetry_apiratelimitconfig_auditlog_and_more'),
        ('tracker', '0004_privacypreference_securitylog_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'Standard User'), ('practitioner', 'Medical Practitioner')], default='user', max_length=20),
        ),
    ]
