# Generated by Django 6.0.2 on 2026-03-02 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_merge_20260302_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedDataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('population_health', 'Population Health'), ('trend_analysis', 'Trend Analysis'), ('aggregate_stats', 'Aggregate Statistics')], max_length=50)),
                ('total_records', models.IntegerField(default=0)),
                ('anonymization_method', models.CharField(blank=True, default='', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('retention_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseScalingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200, unique=True)),
                ('scaling_type', models.CharField(choices=[('read_replica', 'Read Replica'), ('sharding', 'Data Sharding'), ('partitioning', 'Table Partitioning')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('max_connections', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
