# Generated by Django 6.0.2 on 2026-03-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_merge_20260302_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='food_database_id',
            field=models.CharField(blank=True, default='', help_text='External food database identifier (e.g., USDA FDC ID or OpenFoodFacts ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='micronutrientlog',
            name='deficiency_risk',
            field=models.CharField(blank=True, default='', help_text='Risk level mapped from blood test results: low, moderate, high', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Data source: manual, barcode_scan, usda, openfoodfacts', max_length=100),
        ),
    ]
