# Generated by Django 6.0.2 on 2026-03-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_anonymizeddatareport_backupconfiguration_and_more'),
        ('tracker', '0006_foodentry_food_database_id_and_more'),
        ('tracker', '0006_seed_phase11_subtasks'),
    ]

    operations = [
    ]
