# Generated by Django 6.0.2 on 2026-03-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_merge_20260302_0920'),
        ('tracker', '0008_remove_duplicate_subtasks'),
    ]

    operations = [
    ]
