# Generated by Django 6.0.2 on 2026-03-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_merge_20260302_0957'),
        ('tracker', '0010_merge_20260302_1021'),
    ]

    operations = [
    ]
