# Generated by Django 6.0.2 on 2026-03-02 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_merge_20260302_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('genomics', 'Genomics'), ('blockchain', 'Blockchain'), ('reproductive_health', 'Reproductive Health'), ('dicom', 'DICOM'), ('mental_health', 'Mental Health'), ('predictive_analytics', 'Predictive Analytics'), ('ihe_xdm', 'IHE_XDM'), ('machine_learning', 'Machine Learning'), ('macronutrients', 'Macronutrients'), ('micronutrients', 'Micronutrients'), ('nutrition', 'Nutrition'), ('cognitive_tracking', 'Cognitive Tracking'), ('telehealth', 'Telehealth'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('withings', 'Withings'), ('sleep_architecture', 'Sleep Architecture'), ('circadian_rhythm', 'Circadian Rhythm'), ('chronic_disease', 'Chronic Disease'), ('gamification', 'Gamification'), ('hl7_v3', 'HL7 v3'), ('fhir_r4', 'FHIR R4'), ('decentralized_identity', 'Decentralized Identity')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('anomaly_type', models.CharField(choices=[('outlier', 'Statistical Outlier'), ('trend', 'Trend Deviation'), ('pattern', 'Pattern Anomaly'), ('threshold', 'Threshold Breach'), ('correlation', 'Correlation Anomaly')], default='outlier', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField()),
                ('deviation_percent', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('genomics', 'Genomics'), ('blockchain', 'Blockchain'), ('reproductive_health', 'Reproductive Health'), ('dicom', 'DICOM'), ('mental_health', 'Mental Health'), ('predictive_analytics', 'Predictive Analytics'), ('ihe_xdm', 'IHE_XDM'), ('machine_learning', 'Machine Learning'), ('macronutrients', 'Macronutrients'), ('micronutrients', 'Micronutrients'), ('nutrition', 'Nutrition'), ('cognitive_tracking', 'Cognitive Tracking'), ('telehealth', 'Telehealth'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('withings', 'Withings'), ('sleep_architecture', 'Sleep Architecture'), ('circadian_rhythm', 'Circadian Rhythm'), ('chronic_disease', 'Chronic Disease'), ('gamification', 'Gamification'), ('hl7_v3', 'HL7 v3'), ('fhir_r4', 'FHIR R4'), ('decentralized_identity', 'Decentralized Identity')], max_length=50)),
                ('feature_type', models.CharField(choices=[('export', 'Export Capabilities'), ('data_pipeline', 'Data Pipeline'), ('predictive_modeling', 'Predictive Modeling'), ('reporting', 'Reporting Tools'), ('anomaly_detection', 'Anomaly Detection'), ('user_dashboard', 'User Dashboard'), ('api_syncing', 'API Syncing'), ('mobile_integration', 'Mobile Integration'), ('secure_storage', 'Secure Storage'), ('data_visualization', 'Data Visualization'), ('real_time_monitoring', 'Real-Time Monitoring'), ('automated_alerts', 'Automated Alerts')], default='data_pipeline', max_length=50)),
                ('source_description', models.CharField(blank=True, default='', max_length=300)),
                ('destination_description', models.CharField(blank=True, default='', max_length=300)),
                ('frequency', models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='idle', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('genomics', 'Genomics'), ('blockchain', 'Blockchain'), ('reproductive_health', 'Reproductive Health'), ('dicom', 'DICOM'), ('mental_health', 'Mental Health'), ('predictive_analytics', 'Predictive Analytics'), ('ihe_xdm', 'IHE_XDM'), ('machine_learning', 'Machine Learning'), ('macronutrients', 'Macronutrients'), ('micronutrients', 'Micronutrients'), ('nutrition', 'Nutrition'), ('cognitive_tracking', 'Cognitive Tracking'), ('telehealth', 'Telehealth'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('withings', 'Withings'), ('sleep_architecture', 'Sleep Architecture'), ('circadian_rhythm', 'Circadian Rhythm'), ('chronic_disease', 'Chronic Disease'), ('gamification', 'Gamification'), ('hl7_v3', 'HL7 v3'), ('fhir_r4', 'FHIR R4'), ('decentralized_identity', 'Decentralized Identity')], max_length=50)),
                ('feature_type', models.CharField(choices=[('export', 'Export Capabilities'), ('data_pipeline', 'Data Pipeline'), ('predictive_modeling', 'Predictive Modeling'), ('reporting', 'Reporting Tools'), ('anomaly_detection', 'Anomaly Detection'), ('user_dashboard', 'User Dashboard'), ('api_syncing', 'API Syncing'), ('mobile_integration', 'Mobile Integration'), ('secure_storage', 'Secure Storage'), ('data_visualization', 'Data Visualization'), ('real_time_monitoring', 'Real-Time Monitoring'), ('automated_alerts', 'Automated Alerts')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal To'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('neq', 'Not Equal To')], default='gt', max_length=20)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Minimum minutes between repeated alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('genomics', 'Genomics'), ('blockchain', 'Blockchain'), ('reproductive_health', 'Reproductive Health'), ('dicom', 'DICOM'), ('mental_health', 'Mental Health'), ('predictive_analytics', 'Predictive Analytics'), ('ihe_xdm', 'IHE_XDM'), ('machine_learning', 'Machine Learning'), ('macronutrients', 'Macronutrients'), ('micronutrients', 'Micronutrients'), ('nutrition', 'Nutrition'), ('cognitive_tracking', 'Cognitive Tracking'), ('telehealth', 'Telehealth'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('withings', 'Withings'), ('sleep_architecture', 'Sleep Architecture'), ('circadian_rhythm', 'Circadian Rhythm'), ('chronic_disease', 'Chronic Disease'), ('gamification', 'Gamification'), ('hl7_v3', 'HL7 v3'), ('fhir_r4', 'FHIR R4'), ('decentralized_identity', 'Decentralized Identity')], max_length=50)),
                ('model_type', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification'), ('clustering', 'Clustering'), ('time_series', 'Time Series'), ('anomaly', 'Anomaly Detection')], default='regression', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('target_metric', models.CharField(blank=True, default='', max_length=100)),
                ('accuracy_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, default='')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('prediction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureStorageVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('genomics', 'Genomics'), ('blockchain', 'Blockchain'), ('reproductive_health', 'Reproductive Health'), ('dicom', 'DICOM'), ('mental_health', 'Mental Health'), ('predictive_analytics', 'Predictive Analytics'), ('ihe_xdm', 'IHE_XDM'), ('machine_learning', 'Machine Learning'), ('macronutrients', 'Macronutrients'), ('micronutrients', 'Micronutrients'), ('nutrition', 'Nutrition'), ('cognitive_tracking', 'Cognitive Tracking'), ('telehealth', 'Telehealth'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('withings', 'Withings'), ('sleep_architecture', 'Sleep Architecture'), ('circadian_rhythm', 'Circadian Rhythm'), ('chronic_disease', 'Chronic Disease'), ('gamification', 'Gamification'), ('hl7_v3', 'HL7 v3'), ('fhir_r4', 'FHIR R4'), ('decentralized_identity', 'Decentralized Identity')], max_length=50)),
                ('encryption_type', models.CharField(choices=[('aes256', 'AES-256'), ('rsa', 'RSA'), ('hybrid', 'Hybrid (AES+RSA)')], default='aes256', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('archived', 'Archived')], default='active', max_length=20)),
                ('storage_size_mb', models.FloatField(default=0)),
                ('item_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('genomics', 'Genomics'), ('blockchain', 'Blockchain'), ('reproductive_health', 'Reproductive Health'), ('dicom', 'DICOM'), ('mental_health', 'Mental Health'), ('predictive_analytics', 'Predictive Analytics'), ('ihe_xdm', 'IHE_XDM'), ('machine_learning', 'Machine Learning'), ('macronutrients', 'Macronutrients'), ('micronutrients', 'Micronutrients'), ('nutrition', 'Nutrition'), ('cognitive_tracking', 'Cognitive Tracking'), ('telehealth', 'Telehealth'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('withings', 'Withings'), ('sleep_architecture', 'Sleep Architecture'), ('circadian_rhythm', 'Circadian Rhythm'), ('chronic_disease', 'Chronic Disease'), ('gamification', 'Gamification'), ('hl7_v3', 'HL7 v3'), ('fhir_r4', 'FHIR R4'), ('decentralized_identity', 'Decentralized Identity')], max_length=50)),
                ('feature_type', models.CharField(choices=[('export', 'Export Capabilities'), ('data_pipeline', 'Data Pipeline'), ('predictive_modeling', 'Predictive Modeling'), ('reporting', 'Reporting Tools'), ('anomaly_detection', 'Anomaly Detection'), ('user_dashboard', 'User Dashboard'), ('api_syncing', 'API Syncing'), ('mobile_integration', 'Mobile Integration'), ('secure_storage', 'Secure Storage'), ('data_visualization', 'Data Visualization'), ('real_time_monitoring', 'Real-Time Monitoring'), ('automated_alerts', 'Automated Alerts')], max_length=50)),
                ('event_type', models.CharField(choices=[('reading', 'Data Reading'), ('alert', 'Alert Triggered'), ('anomaly', 'Anomaly Detected'), ('sync', 'Data Sync'), ('pipeline', 'Pipeline Event')], default='reading', max_length=20)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical'), ('resolved', 'Resolved')], default='normal', max_length=20)),
                ('metric_name', models.CharField(blank=True, default='', max_length=100)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.monitoringrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
