# Generated by Django 5.2.11 on 2026-03-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_merge_20260302_1059'),
        ('tracker', '0011_merge_20260302_1147'),
    ]

    operations = [
    ]
