# Generated by Django 6.0.3 on 2026-03-04 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_merge_20260302_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secureviewinglink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_viewing_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integrationsubtask',
            name='phase',
            field=models.IntegerField(choices=[(10, 'Genomics & Personalized Medicine'), (11, 'Interoperability'), (12, 'Continuous Monitoring & Alerts')]),
        ),
    ]
