# Generated by Django 6.0.3 on 2026-03-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_merge_20260302_1059'),
    ]

    operations = [
    ]
