# Generated by Django 5.2.11 on 2026-03-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_add_user_to_secure_link_and_health_models'),
        ('tracker', '0012_merge_20260303_2355'),
        ('tracker', '0012_practitioner_access_patient_and_health_data_user_fks'),
    ]

    operations = [
    ]
