# Generated by Django 6.0.3 on 2026-03-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_add_user_to_secure_link_and_health_models'),
        ('tracker', '0012_practitioner_access_patient_and_health_data_user_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioneraccess',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
