# Generated by Django 6.0.3 on 2026-03-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_add_user_to_secure_link_and_health_models'),
        ('tracker', '0012_practitioner_access_patient_and_health_data_user_fks'),
    ]

    operations = [
    ]
