# Generated by Django 6.0.3 on 2026-03-04 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_merge_20260304_1436'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('critical_alert', 'Critical Alert'), ('blood_test_out_of_range', 'Blood Test Out of Range'), ('medication_due', 'Medication Due'), ('health_goal_achieved', 'Health Goal Achieved'), ('weekly_summary', 'Weekly Summary'), ('monthly_report', 'Monthly Report'), ('data_export_ready', 'Data Export Ready'), ('wearable_sync_failed', 'Wearable Sync Failed'), ('custom', 'Custom')], max_length=50)),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of enabled channels, e.g. ["email", "sms"]')),
                ('schedule', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], default='immediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('disabled_events', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('critical_alert', 'Critical Alert'), ('blood_test_out_of_range', 'Blood Test Out of Range'), ('medication_due', 'Medication Due'), ('health_goal_achieved', 'Health Goal Achieved'), ('weekly_summary', 'Weekly Summary'), ('monthly_report', 'Monthly Report'), ('data_export_ready', 'Data Export Ready'), ('wearable_sync_failed', 'Wearable Sync Failed'), ('custom', 'Custom')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('event_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('critical_alert', 'Critical Alert'), ('blood_test_out_of_range', 'Blood Test Out of Range'), ('medication_due', 'Medication Due'), ('health_goal_achieved', 'Health Goal Achieved'), ('weekly_summary', 'Weekly Summary'), ('monthly_report', 'Monthly Report'), ('data_export_ready', 'Data Export Ready'), ('wearable_sync_failed', 'Wearable Sync Failed'), ('custom', 'Custom')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('recipient', models.CharField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tracker.notificationtrigger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
