# Generated by Django 6.0.3 on 2026-03-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_merge_20260304_1422'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='List known allergies, one per line.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, default='', help_text='Chronic conditions or diagnoses, one per line.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medications',
            field=models.TextField(blank=True, default='', help_text='Current medications, one per line.'),
        ),
    ]
