# Generated by Django 6.0.3 on 2026-03-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_merge_20260304_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('habit_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('exercise', 'Exercise'), ('nutrition', 'Nutrition'), ('sleep', 'Sleep'), ('mindfulness', 'Mindfulness'), ('hydration', 'Hydration'), ('medication', 'Medication'), ('other', 'Other')], default='other', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('due_datetime', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
