# Generated by Django 5.2.11 on 2026-03-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_merge_0012_migrations'),
        ('tracker', '0013_merge_20260304_1507'),
    ]

    operations = [
    ]
