# Generated by Django 6.0.3 on 2026-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_habit_log_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
