# Generated by Django 5.2.11 on 2026-03-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_add_language_to_userprofile'),
        ('tracker', '0014_merge_20260304_1523'),
        ('tracker', '0014_notification_system'),
        ('tracker', '0014_user_profile_health_fields'),
        ('tracker', '0015_add_db_indexes'),
    ]

    operations = [
    ]
