# Generated by Django 6.0.3 on 2026-03-04 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_merge_20260304_1532'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('units_per_dose', models.FloatField(default=1.0)),
                ('refill_reminder_threshold', models.PositiveIntegerField(default=7, help_text='Remind when count drops to this many doses')),
                ('last_refill_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('pharmacy_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tracker.medicationschedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_inventories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('skipped', 'Skipped'), ('late', 'Late'), ('prn', 'PRN / As Needed')], default='taken', max_length=20)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=200)),
                ('side_effects', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='tracker.medicationschedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
