# Generated by Django 6.0.3 on 2026-03-04 16:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_medication_log_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('default_unit', models.CharField(blank=True, default='', max_length=50)),
                ('synonyms', models.TextField(blank=True, default='', help_text='Comma-separated list of alternative names for fuzzy matching.')),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('csv', 'CSV'), ('hl7_fhir', 'HL7/FHIR'), ('manual', 'Manual Entry'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('ref_min', models.FloatField(blank=True, null=True)),
                ('ref_max', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Extraction confidence score between 0 and 1.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('raw_name', models.CharField(blank=True, default='', help_text='Original name as it appeared in the source document.', max_length=200)),
                ('raw_line', models.TextField(blank=True, default='', help_text='Original line/row from the source document.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='tracker.measurementtype')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='tracker.sourcedocument')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
