# Generated by Django 6.0.3 on 2026-03-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_medication_log_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('rxcui', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('synonyms', models.TextField(blank=True, default='')),
                ('drug_class', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(default='rxnorm', max_length=50)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='rxcui',
            field=models.CharField(blank=True, default='', help_text='RxNorm Concept Unique Identifier', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacologicalinteraction',
            name='reference_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pharmacologicalinteraction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('rxnorm', 'RxNorm'), ('openfda', 'OpenFDA')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacologicalinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacological_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='tracker.medicationconcept'),
        ),
    ]
