# Generated by Django 5.2.11 on 2026-03-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_merge_20260304_1618'),
        ('tracker', '0017_medication_log_inventory'),
    ]

    operations = [
    ]
