# Generated by Django 6.0.3 on 2026-03-04 16:28

import csv
import os
from django.db import migrations


def populate_measurement_types(apps, schema_editor):
    """Populate MeasurementType from BloodTestInfo if it exists, otherwise from blood_tests.csv."""
    MeasurementType = apps.get_model('tracker', 'MeasurementType')
    BloodTestInfo = apps.get_model('tracker', 'BloodTestInfo')

    rows = list(BloodTestInfo.objects.values('test_name', 'unit', 'normal_min', 'normal_max', 'category'))

    if not rows:
        # Fall back to the bundled CSV
        csv_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
            'blood_tests.csv',
        )
        if os.path.exists(csv_path):
            with open(csv_path, newline='', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    try:
                        normal_min = float(row['normal_min']) if row.get('normal_min') else None
                    except (ValueError, TypeError):
                        normal_min = None
                    try:
                        normal_max = float(row['normal_max']) if row.get('normal_max') else None
                    except (ValueError, TypeError):
                        normal_max = None
                    rows.append({
                        'test_name': row['test_name'],
                        'unit': row.get('unit', ''),
                        'normal_min': normal_min,
                        'normal_max': normal_max,
                        'category': row.get('category', ''),
                    })

    for row in rows:
        MeasurementType.objects.get_or_create(
            name=row['test_name'],
            defaults={
                'default_unit': row.get('unit') or '',
                'normal_min': row.get('normal_min'),
                'normal_max': row.get('normal_max'),
                'category': row.get('category') or '',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_add_measurement_models'),
    ]

    operations = [
        migrations.RunPython(populate_measurement_types, migrations.RunPython.noop),
    ]
