# Generated by Django 5.2.11 on 2026-03-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_add_medication_concept_and_interaction_fields'),
        ('tracker', '0018_merge_20260304_1702'),
    ]

    operations = [
    ]
