# Generated by Django 6.0.3 on 2026-03-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_add_medication_concept_and_interaction_fields'),
        ('tracker', '0019_populate_measurement_types'),
    ]

    operations = [
    ]
