# Generated by Django 6.0.3 on 2026-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_merge_20260304_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='confirmation_notes',
            field=models.TextField(blank=True, default='', help_text='Notes recorded during review/confirmation.'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='Whether this measurement has been reviewed and confirmed.'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='confirmed', help_text='Review workflow status for imported measurements.', max_length=20),
        ),
    ]
