# Generated by Django 6.0.3 on 2026-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_merge_20260304_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationconcept',
            name='dosage_forms',
            field=models.TextField(blank=True, default='', help_text='Available dosage forms (e.g. tablet, capsule).'),
        ),
        migrations.AddField(
            model_name='medicationconcept',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict, help_text='IDs in other databases (FDA, PubChem, etc.).'),
        ),
        migrations.AddField(
            model_name='medicationconcept',
            name='indications',
            field=models.TextField(blank=True, default='', help_text='What the drug is used for.'),
        ),
        migrations.AddField(
            model_name='medicationconcept',
            name='last_enriched',
            field=models.DateTimeField(blank=True, help_text='When enriched data was last fetched.', null=True),
        ),
        migrations.AddField(
            model_name='medicationconcept',
            name='mechanism',
            field=models.TextField(blank=True, default='', help_text='Mechanism of action.'),
        ),
        migrations.AddField(
            model_name='medicationconcept',
            name='side_effects',
            field=models.TextField(blank=True, default='', help_text='Known adverse reactions / side effects.'),
        ),
        migrations.AddField(
            model_name='medicationconcept',
            name='warnings',
            field=models.TextField(blank=True, default='', help_text='Contraindications and important safety warnings.'),
        ),
    ]
