# Generated by Django 5.2.11 on 2026-03-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_merge_20260304_1740'),
        ('tracker', '0020_merge_20260304_1653'),
        ('tracker', '0021_add_medication_concept_enrichment_fields'),
    ]

    operations = [
    ]
