# Generated by Django 6.0.3 on 2026-03-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_add_measurement_review_fields'),
        ('tracker', '0021_add_medication_concept_enrichment_fields'),
    ]

    operations = [
    ]
