# Generated by Django 5.2.11 on 2026-03-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_merge_20260304_1851'),
        ('tracker', '0022_merge_20260304_1921'),
    ]

    operations = [
    ]
