# Generated by Django 6.0.3 on 2026-03-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_merge_20260304_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminTelemetry',
        ),
        migrations.DeleteModel(
            name='AnonymizedDataReport',
        ),
        migrations.DeleteModel(
            name='APIRateLimitConfig',
        ),
        migrations.DeleteModel(
            name='BackupConfiguration',
        ),
        migrations.DeleteModel(
            name='ClinicalTrialMatch',
        ),
        migrations.DeleteModel(
            name='DatabaseScalingConfig',
        ),
        migrations.DeleteModel(
            name='EncryptionKey',
        ),
        migrations.DeleteModel(
            name='TenantConfig',
        ),
    ]
