# Generated by Django 5.2.11 on 2026-03-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_merge_20260304_2103'),
        ('tracker', '0023_remove_dead_placeholder_models'),
    ]

    operations = [
    ]
